<?xml version="1.0" encoding="utf-8"?><Database Name="3342" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.171.36;Initial Catalog=3342;Integrated Security=True" SettingsObjectName="ADOConsoleApp.Properties.Settings" SettingsPropertyName="_3342ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblEmployee" Member="tblEmployees">
    <Type Name="tblEmployee">
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmpSalary" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DeptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblDept_tblEmployee" Member="tblDept" ThisKey="DeptId" OtherKey="DeptId" Type="tblDept" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDept" Member="tblDepts">
    <Type Name="tblDept">
      <Column Name="DeptId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblDept_tblEmployee" Member="tblEmployees" ThisKey="DeptId" OtherKey="DeptId" Type="tblEmployee" />
    </Type>
  </Table>
</Database>